#!/bin/sh
set -e

STABLE_VERSION_REGEX='^6\.0\.[0-9]\+$'

if $(cat "/etc/debian_version" | grep -q -e "$STABLE_VERSION_REGEX"); then
cat > "/etc/apt/preferences" << EOF
Package: debhelper
Pin: release a=squeeze-backports
Pin-Priority: 999

Package: lintian
Pin: release a=squeeze-backports
Pin-Priority: 999

Package: *
Pin: release a=squeeze-backports
Pin-Priority: 700

Package: *
Pin: release n=squeeze-backports
Pin-Priority: 700
EOF
fi
